#MySQL 셋팅
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: Jdbc:mysql://localhost:3306/pharmacy
    username: ${DB_USER}
    password: ${DB_PW}
  sql:
    init:
      mode: ALWAYS
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
